/**
 * Skill Discovery Engine
 * 
 * @module @jclaw/core/skill-sh/discovery
 */

import type { LLMClient } from '../runtime/llm-client.js';
import type { ExtensionRegistry } from '../extension-system/registry.js';
import type { AutoSkillGenerator } from '../auto-skill/generator.js';
import type {
  SkillShResult,
  SkillDiscoveryResult,
} from './types.js';
import type { SkillShAdapter } from './adapter.js';
import type { SkillConverter } from './converter.js';

export class SkillDiscoveryEngine {
  constructor(
    private llmClient: LLMClient,
    private registry: ExtensionRegistry,
    private skillShAdapter: SkillShAdapter,
    private skillConverter: SkillConverter,
    private autoSkillGenerator?: AutoSkillGenerator
  ) {}

  async discover(query: string): Promise<SkillDiscoveryResult> {
    console.log(`🔍 Discovering skills for: "${query}"`);

    const [skillShResults, localMatches] = await Promise.all([
      this.searchSkillSh(query),
      this.searchLocal(query),
    ]);

    console.log(`  Found ${skillShResults.length} skills on skill.sh`);
    console.log(`  Found ${localMatches.length} local matches`);

    const rankedSkillSh = this.rankSkills(skillShResults, query);

    const { recommended, source, confidence } = this.selectBestSource(
      rankedSkillSh,
      localMatches,
      query
    );

    return {
      query,
      skillShResults: rankedSkillSh,
      communityResults: [],
      autoGenerated: undefined,
      recommended,
      confidence,
      source,
    };
  }

  private async searchSkillSh(query: string): Promise<SkillShResult[]> {
    try {
      const results = await this.skillShAdapter.search({
        query,
        sortBy: 'quality',
        limit: 10,
      });

      return results.map(result => ({
        ...result,
        quality: this.assessSkillQuality(result),
      }));
    } catch (error) {
      console.error('skill.sh search failed:', error);
      return [];
    }
  }

  private async searchLocal(query: string): Promise<SkillShResult[]> {
    const keywords = query.toLowerCase().split(' ');
    const results: SkillShResult[] = [];

    for (const ext of this.registry.getAll()) {
      const searchableText = [
        ext.name,
        ext.description,
        ...ext.capabilities.map(c => c.name),
      ].join(' ').toLowerCase();

      const matchScore = keywords.reduce((score, keyword) => {
        if (searchableText.includes(keyword)) score += 1;
        return score;
      }, 0);

      if (matchScore > 0) {
        results.push({
          id: ext.name,
          name: ext.name,
          description: ext.description,
          owner: 'local',
          repo: ext.name,
          stars: 0,
          downloads: 0,
          updatedAt: new Date().toISOString(),
          version: ext.version,
          categories: [],
          tags: [],
          agents: ['jclaw'],
          quality: 90,
          rating: 5,
        });
      }
    }

    return results;
  }

  private rankSkills(skills: SkillShResult[], query: string): SkillShResult[] {
    const queryLower = query.toLowerCase();
    const keywords = queryLower.split(' ');

    return skills
      .map(skill => {
        let score = skill.quality * 0.4;

        if (skill.name.toLowerCase().includes(queryLower)) {
          score += 30;
        }

        const descMatches = keywords.filter(kw =>
          skill.description.toLowerCase().includes(kw)
        ).length;
        score += descMatches * 10;

        const catMatches = keywords.filter(kw =>
          skill.categories.some(cat => cat.toLowerCase().includes(kw))
        ).length;
        score += catMatches * 15;

        if (skill.stars > 100) score += 10;
        else if (skill.stars > 50) score += 5;

        if (skill.downloads > 1000) score += 10;
        else if (skill.downloads > 500) score += 5;

        return { ...skill, relevanceScore: score };
      })
      .sort((a, b) => (b.relevanceScore || 0) - (a.relevanceScore || 0));
  }

  private selectBestSource(
    skillShResults: SkillShResult[],
    localMatches: SkillShResult[],
    query: string
  ): { recommended?: SkillShResult; source: SkillDiscoveryResult['source']; confidence: number } {
    if (localMatches.length > 0) {
      return {
        recommended: localMatches[0],
        source: 'skill.sh',
        confidence: 0.95,
      };
    }

    if (skillShResults.length > 0) {
      const best = skillShResults[0];
      const confidence = this.calculateConfidence(best!, query);
      
      return {
        recommended: best,
        source: 'skill.sh',
        confidence,
      };
    }

    return {
      source: 'none',
      confidence: 0,
    };
  }

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  private calculateConfidence(skill: SkillShResult, _query: string): number {
    let confidence = skill.quality / 100;

    if (skill.stars > 100) confidence += 0.1;
    if (skill.stars > 500) confidence += 0.1;
    if (skill.downloads > 1000) confidence += 0.1;
    if (skill.stars < 10) confidence -= 0.2;
    if (skill.downloads < 50) confidence -= 0.2;

    return Math.min(1, Math.max(0, confidence));
  }

  private assessSkillQuality(skill: SkillShResult): number {
    let score = skill.quality || 50;

    if (skill.stars > 100) score += 10;
    if (skill.downloads > 1000) score += 10;
    if (skill.rating > 4) score += 10;

    const daysSinceUpdate = Math.floor(
      (Date.now() - new Date(skill.updatedAt).getTime()) / (1000 * 60 * 60 * 24)
    );
    if (daysSinceUpdate < 30) score += 10;
    else if (daysSinceUpdate < 90) score += 5;

    return Math.min(100, score);
  }

  async installSkill(skill: SkillShResult): Promise<boolean> {
    try {
      console.log(`📦 Installing skill: ${skill.id}`);
      const result = await this.skillShAdapter.installSkill(skill.id);
      
      if (!result.success) {
        console.error(`  ❌ Failed: ${result.error}`);
        return false;
      }

      if (result.installPath) {
        console.log(`  ✅ Installed to: ${result.installPath}`);
      }

      return true;
    } catch (error) {
      console.error('Failed to install skill:', error);
      return false;
    }
  }
}

export function createSkillDiscoveryEngine(
  llmClient: LLMClient,
  registry: ExtensionRegistry,
  skillShAdapter: SkillShAdapter,
  skillConverter: SkillConverter,
  autoSkillGenerator?: AutoSkillGenerator
): SkillDiscoveryEngine {
  return new SkillDiscoveryEngine(
    llmClient,
    registry,
    skillShAdapter,
    skillConverter,
    autoSkillGenerator
  );
}
