/**
 * Skill.sh Integration Types
 * 
 * Type definitions for skill.sh ecosystem integration
 * 
 * @module @jclaw/core/skill-sh/types
 */

import type { Extension } from '../types.js';

/**
 * Skill.sh search result
 */
export interface SkillShResult {
  /** Skill ID (owner/repo format) */
  id: string;
  /** Skill name */
  name: string;
  /** Short description */
  description: string;
  /** GitHub owner */
  owner: string;
  /** GitHub repo */
  repo: string;
  /** GitHub stars */
  stars: number;
  /** Download count */
  downloads: number;
  /** Last updated */
  updatedAt: string;
  /** Skill version */
  version: string;
  /** Categories */
  categories: string[];
  /** Tags */
  tags: string[];
  /** Compatible agents */
  agents: string[];
  /** Quality score (0-100) */
  quality: number;
  /** Community rating */
  rating: number;
}

/**
 * Skill detail information
 */
export interface SkillShDetail extends SkillShResult {
  /** Full README content */
  readme: string;
  /** SKILL.md content */
  skillMd: string;
  /** Example usage */
  examples: string[];
  /** Required permissions */
  permissions: string[];
  /** Dependencies */
  dependencies: string[];
  /** Installation command */
  installCommand: string;
  /** File size */
  size: number;
  /** License */
  license: string;
}

/**
 * SKILL.md frontmatter structure
 */
export interface SkillFrontmatter {
  /** Skill name */
  name: string;
  /** Short description */
  description: string;
  /** Version */
  version?: string;
  /** Author */
  author?: string;
  /** Categories */
  categories?: string[];
  /** Tags */
  tags?: string[];
  /** Compatible agents */
  agents?: string[];
  /** Required permissions */
  permissions?: string[];
  /** Minimum JClaw version */
  minJClawVersion?: string;
}

/**
 * Converted JClaw Extension from Skill
 */
export interface ConvertedSkill {
  /** Original skill info */
  original: SkillShResult;
  /** Converted extension */
  extension: Extension;
  /** Conversion quality score */
  quality: number;
  /** Warnings during conversion */
  warnings: string[];
}

/**
 * Skill search options
 */
export interface SkillSearchOptions {
  /** Search query */
  query: string;
  /** Filter by category */
  category?: string;
  /** Minimum quality score */
  minQuality?: number;
  /** Sort by */
  sortBy?: 'relevance' | 'stars' | 'downloads' | 'quality' | 'updated';
  /** Limit results */
  limit?: number;
  /** Filter by compatible agents */
  agents?: string[];
}

/**
 * Skill discovery result
 */
export interface SkillDiscoveryResult {
  /** Search query */
  query: string;
  /** Found skills from skill.sh */
  skillShResults: SkillShResult[];
  /** Found skills from community repo */
  communityResults: SkillShResult[];
  /** Auto-generated alternative */
  autoGenerated?: ConvertedSkill;
  /** Recommended skill (best match) */
  recommended?: SkillShResult;
  /** Confidence score (0-1) */
  confidence: number;
  /** Source of recommendation */
  source: 'skill.sh' | 'community' | 'autogenerated' | 'none';
}

/**
 * Skill installation result
 */
export interface SkillInstallationResult {
  /** Success status */
  success: boolean;
  /** Installed skill */
  skill?: SkillShResult;
  /** Installed extension */
  extension?: Extension;
  /** Installation path */
  installPath?: string;
  /** Error message if failed */
  error?: string;
  /** Installation duration */
  duration: number;
}

/**
 * Skill registry entry
 */
export interface SkillRegistryEntry {
  /** Skill ID */
  id: string;
  /** Installation status */
  status: 'installed' | 'active' | 'error' | 'deprecated';
  /** Installation path */
  path: string;
  /** Installed version */
  version: string;
  /** Installation date */
  installedAt: Date;
  /** Last used */
  lastUsedAt?: Date;
  /** Usage count */
  usageCount: number;
  /** User rating */
  userRating?: number;
  /** Local quality assessment */
  localQuality: number;
}

/**
 * Skill quality assessment
 */
export interface SkillQualityAssessment {
  /** Overall score (0-100) */
  score: number;
  /** Code quality (0-100) */
  codeQuality: number;
  /** Documentation quality (0-100) */
  documentation: number;
  /** Test coverage (0-100) */
  testCoverage: number;
  /** Community adoption (0-100) */
  community: number;
  /** Security assessment (0-100) */
  security: number;
  /** Detailed breakdown */
  details: {
    /** Lines of code */
    linesOfCode: number;
    /** Has tests */
    hasTests: boolean;
    /** Has examples */
    hasExamples: boolean;
    /** Has documentation */
    hasDocumentation: boolean;
    /** Last update within 30 days */
    recentlyUpdated: boolean;
    /** Has open issues */
    openIssues: number;
  };
}

/**
 * Skill.sh adapter configuration
 */
export interface SkillShAdapterConfig {
  /** API base URL */
  apiBase?: string;
  /** Cache directory */
  cacheDir?: string;
  /** Enable caching */
  enableCache?: boolean;
  /** Cache TTL (ms) */
  cacheTtl?: number;
  /** Request timeout (ms) */
  timeout?: number;
  /** User agent */
  userAgent?: string;
  /** GitHub token for higher rate limits */
  githubToken?: string;
  /** Community repo URL */
  communityRepo?: string;
}
